var annotated_dup =
[
    [ "std", null, [
      [ "formatter< S, typename S::value_type >", "structstd_1_1formatter_3_01S_00_01typename_01S_1_1value__type_01_4.html", "structstd_1_1formatter_3_01S_00_01typename_01S_1_1value__type_01_4" ],
      [ "formatter< T, CharT >", "structstd_1_1formatter_3_01T_00_01CharT_01_4.html", "structstd_1_1formatter_3_01T_00_01CharT_01_4" ],
      [ "numeric_limits< T >", "structstd_1_1numeric__limits_3_01T_01_4.html", null ]
    ] ],
    [ "utils", "namespaceutils.html", [
      [ "bit_behavior", "namespaceutils_1_1bit__behavior.html", [
        [ "default_asg_op_traits", "structutils_1_1bit__behavior_1_1default__asg__op__traits.html", [
          [ "constraint", "structutils_1_1bit__behavior_1_1default__asg__op__traits_1_1constraint.html", null ]
        ] ],
        [ "default_binary_op_traits", "structutils_1_1bit__behavior_1_1default__binary__op__traits.html", [
          [ "constraint", "structutils_1_1bit__behavior_1_1default__binary__op__traits_1_1constraint.html", null ],
          [ "result", "structutils_1_1bit__behavior_1_1default__binary__op__traits_1_1result.html", "structutils_1_1bit__behavior_1_1default__binary__op__traits_1_1result" ]
        ] ],
        [ "profile", "structutils_1_1bit__behavior_1_1profile.html", null ]
      ] ],
      [ "integral_behavior", "namespaceutils_1_1integral__behavior.html", [
        [ "default_asg_op_traits", "structutils_1_1integral__behavior_1_1default__asg__op__traits.html", [
          [ "constraint", "structutils_1_1integral__behavior_1_1default__asg__op__traits_1_1constraint.html", null ]
        ] ],
        [ "default_binary_op_traits", "structutils_1_1integral__behavior_1_1default__binary__op__traits.html", [
          [ "constraint", "structutils_1_1integral__behavior_1_1default__binary__op__traits_1_1constraint.html", null ],
          [ "result", "structutils_1_1integral__behavior_1_1default__binary__op__traits_1_1result.html", "structutils_1_1integral__behavior_1_1default__binary__op__traits_1_1result" ]
        ] ],
        [ "profile", "structutils_1_1integral__behavior_1_1profile.html", null ]
      ] ],
      [ "meta", "namespaceutils_1_1meta.html", [
        [ "actual_index", "structutils_1_1meta_1_1actual__index.html", null ],
        [ "at", "structutils_1_1meta_1_1at.html", "structutils_1_1meta_1_1at" ],
        [ "bind_back", "structutils_1_1meta_1_1bind__back.html", [
          [ "trait", "structutils_1_1meta_1_1bind__back_1_1trait.html", null ]
        ] ],
        [ "bind_front", "structutils_1_1meta_1_1bind__front.html", [
          [ "trait", "structutils_1_1meta_1_1bind__front_1_1trait.html", null ]
        ] ],
        [ "concat", "structutils_1_1meta_1_1concat.html", "structutils_1_1meta_1_1concat" ],
        [ "const_var", "classutils_1_1meta_1_1const__var.html", "classutils_1_1meta_1_1const__var" ],
        [ "contained_in", "structutils_1_1meta_1_1contained__in.html", null ],
        [ "contained_in_trait", "structutils_1_1meta_1_1contained__in__trait.html", null ],
        [ "define", "classutils_1_1meta_1_1define.html", "classutils_1_1meta_1_1define" ],
        [ "erase", "structutils_1_1meta_1_1erase.html", null ],
        [ "extract", "structutils_1_1meta_1_1extract.html", null ],
        [ "extract< Tmpl< Args... > >", "structutils_1_1meta_1_1extract_3_01Tmpl_3_01Args_8_8_8_01_4_01_4.html", "structutils_1_1meta_1_1extract_3_01Tmpl_3_01Args_8_8_8_01_4_01_4" ],
        [ "infer", "structutils_1_1meta_1_1infer.html", "structutils_1_1meta_1_1infer" ],
        [ "insert", "structutils_1_1meta_1_1insert.html", null ],
        [ "is_tuple", "structutils_1_1meta_1_1is__tuple.html", null ],
        [ "is_tuple< std::tuple< Ts... > >", "structutils_1_1meta_1_1is__tuple_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
        [ "make_tuple", "structutils_1_1meta_1_1make__tuple.html", null ],
        [ "map", "structutils_1_1meta_1_1map.html", null ],
        [ "pack", "structutils_1_1meta_1_1pack.html", "structutils_1_1meta_1_1pack" ],
        [ "product", "structutils_1_1meta_1_1product.html", null ],
        [ "product_t", "structutils_1_1meta_1_1product__t.html", null ],
        [ "rebind", "structutils_1_1meta_1_1rebind.html", "structutils_1_1meta_1_1rebind" ],
        [ "rebind< T, Args... >", "structutils_1_1meta_1_1rebind_3_01T_00_01Args_8_8_8_01_4.html", "structutils_1_1meta_1_1rebind_3_01T_00_01Args_8_8_8_01_4" ],
        [ "reduce", "structutils_1_1meta_1_1reduce.html", null ],
        [ "reduce< Trait, std::tuple< Ts... > >", "structutils_1_1meta_1_1reduce_3_01Trait_00_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
        [ "replace", "structutils_1_1meta_1_1replace.html", null ],
        [ "search", "structutils_1_1meta_1_1search.html", null ],
        [ "search< Tuple, T, PredTrait, End, End >", "structutils_1_1meta_1_1search_3_01Tuple_00_01T_00_01PredTrait_00_01End_00_01End_01_4.html", null ],
        [ "search_trait", "structutils_1_1meta_1_1search__trait.html", null ],
        [ "set", "classutils_1_1meta_1_1set.html", "classutils_1_1meta_1_1set" ],
        [ "slice", "structutils_1_1meta_1_1slice.html", "structutils_1_1meta_1_1slice" ],
        [ "smart_pack", "structutils_1_1meta_1_1smart__pack.html", "structutils_1_1meta_1_1smart__pack" ],
        [ "smart_pack< std::tuple< Ts... > >", "structutils_1_1meta_1_1smart__pack_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", "structutils_1_1meta_1_1smart__pack_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4" ],
        [ "subset_of", "structutils_1_1meta_1_1subset__of.html", null ],
        [ "sum", "structutils_1_1meta_1_1sum.html", null ],
        [ "var", "classutils_1_1meta_1_1var.html", "classutils_1_1meta_1_1var" ]
      ] ],
      [ "pmr", "namespaceutils_1_1pmr.html", [
        [ "allocator_base", "structutils_1_1pmr_1_1allocator__base.html", "structutils_1_1pmr_1_1allocator__base" ],
        [ "allocator_resource", "classutils_1_1pmr_1_1allocator__resource.html", "classutils_1_1pmr_1_1allocator__resource" ],
        [ "arena_allocator", "classutils_1_1pmr_1_1arena__allocator.html", "classutils_1_1pmr_1_1arena__allocator" ],
        [ "stack_allocator", "classutils_1_1pmr_1_1stack__allocator.html", "classutils_1_1pmr_1_1stack__allocator" ]
      ] ],
      [ "shift_behavior", "namespaceutils_1_1shift__behavior.html", [
        [ "default_binary_op_traits", "structutils_1_1shift__behavior_1_1default__binary__op__traits.html", [
          [ "result", "structutils_1_1shift__behavior_1_1default__binary__op__traits_1_1result.html", "structutils_1_1shift__behavior_1_1default__binary__op__traits_1_1result" ]
        ] ],
        [ "profile", "structutils_1_1shift__behavior_1_1profile.html", null ]
      ] ],
      [ "aligned_t", "structutils_1_1aligned__t.html", "structutils_1_1aligned__t" ],
      [ "always_false", "structutils_1_1always__false.html", null ],
      [ "always_true", "structutils_1_1always__true.html", null ],
      [ "apply_qualifiers", "structutils_1_1apply__qualifiers.html", "structutils_1_1apply__qualifiers" ],
      [ "arguments_of", "structutils_1_1arguments__of.html", null ],
      [ "arguments_of< R(Args...)>", "structutils_1_1arguments__of_3_01R_07Args_8_8_8_08_4.html", "structutils_1_1arguments__of_3_01R_07Args_8_8_8_08_4" ],
      [ "arithmetic_ops", "structutils_1_1arithmetic__ops.html", null ],
      [ "arity", "structutils_1_1arity.html", null ],
      [ "arity_of", "structutils_1_1arity__of.html", null ],
      [ "arity_of< R(Args...)>", "structutils_1_1arity__of_3_01R_07Args_8_8_8_08_4.html", null ],
      [ "asg_wrap", "structutils_1_1asg__wrap.html", null ],
      [ "asg_wrap< Op, void >", "structutils_1_1asg__wrap_3_01Op_00_01void_01_4.html", null ],
      [ "basic_static_string", "structutils_1_1basic__static__string.html", "structutils_1_1basic__static__string" ],
      [ "basic_static_string_view", "structutils_1_1basic__static__string__view.html", "structutils_1_1basic__static__string__view" ],
      [ "bind", "structutils_1_1bind.html", "structutils_1_1bind" ],
      [ "bit_asg_op_functors", "structutils_1_1bit__asg__op__functors.html", "structutils_1_1bit__asg__op__functors" ],
      [ "bit_asg_ops", "structutils_1_1bit__asg__ops.html", null ],
      [ "bit_full_ops", "structutils_1_1bit__full__ops.html", null ],
      [ "bit_op_functors", "structutils_1_1bit__op__functors.html", "structutils_1_1bit__op__functors" ],
      [ "bit_ops", "structutils_1_1bit__ops.html", null ],
      [ "cast", "structutils_1_1cast.html", null ],
      [ "cast< To, void >", "structutils_1_1cast_3_01To_00_01void_01_4.html", null ],
      [ "cast_transform", "structutils_1_1cast__transform.html", null ],
      [ "common_cast_transform", "structutils_1_1common__cast__transform.html", null ],
      [ "compile_error", "classutils_1_1compile__error.html", "classutils_1_1compile__error" ],
      [ "copy_construct", "structutils_1_1copy__construct.html", null ],
      [ "copy_construct<>", "structutils_1_1copy__construct_3_4.html", null ],
      [ "default_asg_op_traits", "structutils_1_1default__asg__op__traits.html", [
        [ "constraint", "structutils_1_1default__asg__op__traits_1_1constraint.html", null ]
      ] ],
      [ "default_binary_op_traits", "structutils_1_1default__binary__op__traits.html", [
        [ "constraint", "structutils_1_1default__binary__op__traits_1_1constraint.html", null ],
        [ "result", "structutils_1_1default__binary__op__traits_1_1result.html", null ]
      ] ],
      [ "default_construct", "structutils_1_1default__construct.html", null ],
      [ "default_postfix_op_traits", "structutils_1_1default__postfix__op__traits.html", [
        [ "constraint", "structutils_1_1default__postfix__op__traits_1_1constraint.html", null ],
        [ "result", "structutils_1_1default__postfix__op__traits_1_1result.html", null ]
      ] ],
      [ "default_prefix_op_traits", "structutils_1_1default__prefix__op__traits.html", [
        [ "constraint", "structutils_1_1default__prefix__op__traits_1_1constraint.html", null ],
        [ "result", "structutils_1_1default__prefix__op__traits_1_1result.html", null ]
      ] ],
      [ "default_unary_op_traits", "structutils_1_1default__unary__op__traits.html", [
        [ "constraint", "structutils_1_1default__unary__op__traits_1_1constraint.html", null ],
        [ "result", "structutils_1_1default__unary__op__traits_1_1result.html", null ]
      ] ],
      [ "disable_op_t", "structutils_1_1disable__op__t.html", null ],
      [ "epsilon_of", "structutils_1_1epsilon__of.html", null ],
      [ "filter_iterator", "classutils_1_1filter__iterator.html", "classutils_1_1filter__iterator" ],
      [ "fix_op_functors", "structutils_1_1fix__op__functors.html", "structutils_1_1fix__op__functors" ],
      [ "fix_ops", "structutils_1_1fix__ops.html", null ],
      [ "follow", "structutils_1_1follow.html", "structutils_1_1follow" ],
      [ "function_decay", "structutils_1_1function__decay.html", null ],
      [ "function_decay< R(Args...) noexcept >", "structutils_1_1function__decay_3_01R_07Args_8_8_8_08_01noexcept_01_4.html", "structutils_1_1function__decay_3_01R_07Args_8_8_8_08_01noexcept_01_4" ],
      [ "function_decay< R(Args...)>", "structutils_1_1function__decay_3_01R_07Args_8_8_8_08_4.html", "structutils_1_1function__decay_3_01R_07Args_8_8_8_08_4" ],
      [ "function_decay< T >", "structutils_1_1function__decay_3_01T_01_4.html", null ],
      [ "integer", "structutils_1_1integer.html", "structutils_1_1integer" ],
      [ "integral_asg_op_functors", "structutils_1_1integral__asg__op__functors.html", "structutils_1_1integral__asg__op__functors" ],
      [ "integral_asg_ops", "structutils_1_1integral__asg__ops.html", null ],
      [ "integral_full_ops", "structutils_1_1integral__full__ops.html", null ],
      [ "integral_op_functors", "structutils_1_1integral__op__functors.html", "structutils_1_1integral__op__functors" ],
      [ "integral_ops", "structutils_1_1integral__ops.html", null ],
      [ "interval", "structutils_1_1interval.html", "structutils_1_1interval" ],
      [ "interval_endpoint", "structutils_1_1interval__endpoint.html", "structutils_1_1interval__endpoint" ],
      [ "is_equiv", "structutils_1_1is__equiv.html", null ],
      [ "is_explicitly_convertible", "structutils_1_1is__explicitly__convertible.html", null ],
      [ "is_integer_like", "structutils_1_1is__integer__like.html", null ],
      [ "is_integer_like< const T >", "structutils_1_1is__integer__like_3_01const_01T_01_4.html", null ],
      [ "is_integer_like< const volatile T >", "structutils_1_1is__integer__like_3_01const_01volatile_01T_01_4.html", null ],
      [ "is_integer_like< T >", "structutils_1_1is__integer__like_3_01T_01_4.html", null ],
      [ "is_integer_like< volatile T >", "structutils_1_1is__integer__like_3_01volatile_01T_01_4.html", null ],
      [ "is_same_sign", "structutils_1_1is__same__sign.html", null ],
      [ "is_tagged", "structutils_1_1is__tagged.html", null ],
      [ "is_template_instance", "structutils_1_1is__template__instance.html", null ],
      [ "is_template_instance< Tmpl, Tmpl< Ts... > >", "structutils_1_1is__template__instance_3_01Tmpl_00_01Tmpl_3_01Ts_8_8_8_01_4_01_4.html", null ],
      [ "iterator_category", "structutils_1_1iterator__category.html", "structutils_1_1iterator__category" ],
      [ "joint_cast_transform", "structutils_1_1joint__cast__transform.html", null ],
      [ "key", "classutils_1_1key.html", null ],
      [ "lambda_decay", "structutils_1_1lambda__decay.html", null ],
      [ "lambda_decay< R(&)(Args...) noexcept >", "structutils_1_1lambda__decay_3_01R_07_6_08_07Args_8_8_8_08_01noexcept_01_4.html", "structutils_1_1lambda__decay_3_01R_07_6_08_07Args_8_8_8_08_01noexcept_01_4" ],
      [ "lambda_decay< R(&)(Args...)>", "structutils_1_1lambda__decay_3_01R_07_6_08_07Args_8_8_8_08_4.html", "structutils_1_1lambda__decay_3_01R_07_6_08_07Args_8_8_8_08_4" ],
      [ "lambda_decay< T >", "structutils_1_1lambda__decay_3_01T_01_4.html", null ],
      [ "logical_op_functors", "structutils_1_1logical__op__functors.html", "structutils_1_1logical__op__functors" ],
      [ "logical_ops", "structutils_1_1logical__ops.html", null ],
      [ "max_align", "structutils_1_1max__align.html", null ],
      [ "move_construct", "structutils_1_1move__construct.html", null ],
      [ "move_construct<>", "structutils_1_1move__construct_3_4.html", null ],
      [ "owning", "structutils_1_1owning.html", null ],
      [ "pointer_iterator", "classutils_1_1pointer__iterator.html", "classutils_1_1pointer__iterator" ],
      [ "post_decrement", "structutils_1_1post__decrement.html", null ],
      [ "post_decrement<>", "structutils_1_1post__decrement_3_4.html", null ],
      [ "post_increment", "structutils_1_1post__increment.html", null ],
      [ "post_increment<>", "structutils_1_1post__increment_3_4.html", null ],
      [ "pre_decrement", "structutils_1_1pre__decrement.html", null ],
      [ "pre_decrement< void >", "structutils_1_1pre__decrement_3_01void_01_4.html", null ],
      [ "pre_increment", "structutils_1_1pre__increment.html", null ],
      [ "pre_increment< void >", "structutils_1_1pre__increment_3_01void_01_4.html", null ],
      [ "promote", "structutils_1_1promote.html", null ],
      [ "promote< void >", "structutils_1_1promote_3_01void_01_4.html", null ],
      [ "qualifiers_of", "structutils_1_1qualifiers__of.html", null ],
      [ "result_of", "structutils_1_1result__of.html", null ],
      [ "result_of< R(Args...)>", "structutils_1_1result__of_3_01R_07Args_8_8_8_08_4.html", "structutils_1_1result__of_3_01R_07Args_8_8_8_08_4" ],
      [ "sane_common_type", "structutils_1_1sane__common__type.html", null ],
      [ "sane_common_type< T, U >", "structutils_1_1sane__common__type_3_01T_00_01U_01_4.html", "structutils_1_1sane__common__type_3_01T_00_01U_01_4" ],
      [ "shift_asg_op_functors", "structutils_1_1shift__asg__op__functors.html", "structutils_1_1shift__asg__op__functors" ],
      [ "shift_asg_ops", "structutils_1_1shift__asg__ops.html", null ],
      [ "shift_full_ops", "structutils_1_1shift__full__ops.html", null ],
      [ "shift_left", "structutils_1_1shift__left.html", null ],
      [ "shift_left< void >", "structutils_1_1shift__left_3_01void_01_4.html", null ],
      [ "shift_left_asg", "structutils_1_1shift__left__asg.html", null ],
      [ "shift_left_asg< void >", "structutils_1_1shift__left__asg_3_01void_01_4.html", null ],
      [ "shift_op_functors", "structutils_1_1shift__op__functors.html", "structutils_1_1shift__op__functors" ],
      [ "shift_ops", "structutils_1_1shift__ops.html", null ],
      [ "shift_right", "structutils_1_1shift__right.html", null ],
      [ "shift_right< void >", "structutils_1_1shift__right_3_01void_01_4.html", null ],
      [ "shift_right_asg", "structutils_1_1shift__right__asg.html", null ],
      [ "shift_right_asg< void >", "structutils_1_1shift__right__asg_3_01void_01_4.html", null ],
      [ "sign_op_functors", "structutils_1_1sign__op__functors.html", "structutils_1_1sign__op__functors" ],
      [ "sign_ops", "structutils_1_1sign__ops.html", null ],
      [ "sink", "structutils_1_1sink.html", "structutils_1_1sink" ],
      [ "stale_class", "structutils_1_1stale__class.html", "structutils_1_1stale__class" ],
      [ "synth_three_way_result", "structutils_1_1synth__three__way__result.html", "structutils_1_1synth__three__way__result" ],
      [ "transform_iterator", "classutils_1_1transform__iterator.html", "classutils_1_1transform__iterator" ],
      [ "trim", "structutils_1_1trim.html", null ],
      [ "trivial_semaphore", "structutils_1_1trivial__semaphore.html", "structutils_1_1trivial__semaphore" ],
      [ "unique_resource", "classutils_1_1unique__resource.html", "classutils_1_1unique__resource" ],
      [ "unique_resource_sync_t", "structutils_1_1unique__resource__sync__t.html", null ],
      [ "visitor", "classutils_1_1visitor.html", "classutils_1_1visitor" ],
      [ "width_of", "structutils_1_1width__of.html", null ],
      [ "with", "structutils_1_1with.html", "structutils_1_1with" ]
    ] ]
];