var annotated_dup =
[
    [ "std", null, [
      [ "formatter< T, CharT >", "structstd_1_1formatter_3_01T_00_01CharT_01_4.html", "structstd_1_1formatter_3_01T_00_01CharT_01_4" ],
      [ "numeric_limits< T >", "structstd_1_1numeric__limits_3_01T_01_4.html", "structstd_1_1numeric__limits_3_01T_01_4" ]
    ] ],
    [ "utils", "namespaceutils.html", [
      [ "detail", "namespaceutils_1_1detail.html", [
        [ "arity_psum", "structutils_1_1detail_1_1arity__psum.html", "structutils_1_1detail_1_1arity__psum" ],
        [ "arity_psum< WrapsT, 0 >", "structutils_1_1detail_1_1arity__psum_3_01WrapsT_00_010_01_4.html", "structutils_1_1detail_1_1arity__psum_3_01WrapsT_00_010_01_4" ],
        [ "bound_dyn_method", "structutils_1_1detail_1_1bound__dyn__method.html", "structutils_1_1detail_1_1bound__dyn__method" ],
        [ "dyn_method_base", "classutils_1_1detail_1_1dyn__method__base.html", "classutils_1_1detail_1_1dyn__method__base" ],
        [ "ivtable_pointers", "structutils_1_1detail_1_1ivtable__pointers.html", "structutils_1_1detail_1_1ivtable__pointers" ],
        [ "ivtable_pointers< std::tuple< Is... > >", "structutils_1_1detail_1_1ivtable__pointers_3_01std_1_1tuple_3_01Is_8_8_8_01_4_01_4.html", null ],
        [ "sequence_apply", "structutils_1_1detail_1_1sequence__apply.html", null ],
        [ "sequence_apply< T, F, std::integer_sequence< T, Ns... > >", "structutils_1_1detail_1_1sequence__apply_3_01T_00_01F_00_01std_1_1integer__sequence_3_01T_00_01Ns_8_8_8_01_4_01_4.html", "structutils_1_1detail_1_1sequence__apply_3_01T_00_01F_00_01std_1_1integer__sequence_3_01T_00_01Ns_8_8_8_01_4_01_4" ],
        [ "unique_resource_typedefs", "structutils_1_1detail_1_1unique__resource__typedefs.html", "structutils_1_1detail_1_1unique__resource__typedefs" ],
        [ "unique_resource_typedefs< false, SharedMutex >", "structutils_1_1detail_1_1unique__resource__typedefs_3_01false_00_01SharedMutex_01_4.html", null ]
      ] ],
      [ "integral_behavior", "namespaceutils_1_1integral__behavior.html", [
        [ "checked", "structutils_1_1integral__behavior_1_1checked.html", "structutils_1_1integral__behavior_1_1checked" ],
        [ "sane", "structutils_1_1integral__behavior_1_1sane.html", "structutils_1_1integral__behavior_1_1sane" ],
        [ "standard", "structutils_1_1integral__behavior_1_1standard.html", "structutils_1_1integral__behavior_1_1standard" ],
        [ "ub", "structutils_1_1integral__behavior_1_1ub.html", "structutils_1_1integral__behavior_1_1ub" ],
        [ "wrap", "structutils_1_1integral__behavior_1_1wrap.html", "structutils_1_1integral__behavior_1_1wrap" ]
      ] ],
      [ "meta", "namespaceutils_1_1meta.html", [
        [ "detail", "namespaceutils_1_1meta_1_1detail.html", [
          [ "counter", "structutils_1_1meta_1_1detail_1_1counter.html", null ],
          [ "make_tuple", "structutils_1_1meta_1_1detail_1_1make__tuple.html", null ],
          [ "make_tuple< T, std::index_sequence< Idxs... > >", "structutils_1_1meta_1_1detail_1_1make__tuple_3_01T_00_01std_1_1index__sequence_3_01Idxs_8_8_8_01_4_01_4.html", "structutils_1_1meta_1_1detail_1_1make__tuple_3_01T_00_01std_1_1index__sequence_3_01Idxs_8_8_8_01_4_01_4" ],
          [ "map", "structutils_1_1meta_1_1detail_1_1map.html", null ],
          [ "map< Trait, TuplesTuple, std::index_sequence< Idxs... > >", "structutils_1_1meta_1_1detail_1_1map_3_01Trait_00_01TuplesTuple_00_01std_1_1index__sequence_3_01Idxs_8_8_8_01_4_01_4.html", "structutils_1_1meta_1_1detail_1_1map_3_01Trait_00_01TuplesTuple_00_01std_1_1index__sequence_3_01Idxs_8_8_8_01_4_01_4" ],
          [ "map_step", "structutils_1_1meta_1_1detail_1_1map__step.html", null ],
          [ "map_step< Idx, Trait, std::tuple< Tuples... > >", "structutils_1_1meta_1_1detail_1_1map__step_3_01Idx_00_01Trait_00_01std_1_1tuple_3_01Tuples_8_8_8_01_4_01_4.html", "structutils_1_1meta_1_1detail_1_1map__step_3_01Idx_00_01Trait_00_01std_1_1tuple_3_01Tuples_8_8_8_01_4_01_4" ],
          [ "slice", "structutils_1_1meta_1_1detail_1_1slice.html", null ],
          [ "slice< Tuple, Begin, std::index_sequence< RelIdxs... > >", "structutils_1_1meta_1_1detail_1_1slice_3_01Tuple_00_01Begin_00_01std_1_1index__sequence_3_01RelIdxs_8_8_8_01_4_01_4.html", "structutils_1_1meta_1_1detail_1_1slice_3_01Tuple_00_01Begin_00_01std_1_1index__sequence_3_01RelIdxs_8_8_8_01_4_01_4" ]
        ] ],
        [ "actual_index", "structutils_1_1meta_1_1actual__index.html", null ],
        [ "at", "structutils_1_1meta_1_1at.html", "structutils_1_1meta_1_1at" ],
        [ "bind_back", "structutils_1_1meta_1_1bind__back.html", [
          [ "trait", "structutils_1_1meta_1_1bind__back_1_1trait.html", null ]
        ] ],
        [ "bind_front", "structutils_1_1meta_1_1bind__front.html", [
          [ "trait", "structutils_1_1meta_1_1bind__front_1_1trait.html", null ]
        ] ],
        [ "concat", "structutils_1_1meta_1_1concat.html", "structutils_1_1meta_1_1concat" ],
        [ "const_var", "classutils_1_1meta_1_1const__var.html", "classutils_1_1meta_1_1const__var" ],
        [ "contained_in", "structutils_1_1meta_1_1contained__in.html", null ],
        [ "contained_in_trait", "structutils_1_1meta_1_1contained__in__trait.html", null ],
        [ "define", "classutils_1_1meta_1_1define.html", "classutils_1_1meta_1_1define" ],
        [ "erase", "structutils_1_1meta_1_1erase.html", null ],
        [ "infer", "structutils_1_1meta_1_1infer.html", "structutils_1_1meta_1_1infer" ],
        [ "insert", "structutils_1_1meta_1_1insert.html", null ],
        [ "is_tuple", "structutils_1_1meta_1_1is__tuple.html", null ],
        [ "is_tuple< std::tuple< Ts... > >", "structutils_1_1meta_1_1is__tuple_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
        [ "make_tuple", "structutils_1_1meta_1_1make__tuple.html", null ],
        [ "map", "structutils_1_1meta_1_1map.html", null ],
        [ "pack", "structutils_1_1meta_1_1pack.html", "structutils_1_1meta_1_1pack" ],
        [ "product", "structutils_1_1meta_1_1product.html", null ],
        [ "reduce", "structutils_1_1meta_1_1reduce.html", null ],
        [ "reduce< Trait, std::tuple< Ts... > >", "structutils_1_1meta_1_1reduce_3_01Trait_00_01std_1_1tuple_3_01Ts_8_8_8_01_4_01_4.html", null ],
        [ "replace", "structutils_1_1meta_1_1replace.html", null ],
        [ "search", "structutils_1_1meta_1_1search.html", null ],
        [ "search< Tuple, T, PredTrait, End, End >", "structutils_1_1meta_1_1search_3_01Tuple_00_01T_00_01PredTrait_00_01End_00_01End_01_4.html", null ],
        [ "search_trait", "structutils_1_1meta_1_1search__trait.html", null ],
        [ "slice", "structutils_1_1meta_1_1slice.html", "structutils_1_1meta_1_1slice" ],
        [ "subset_of", "structutils_1_1meta_1_1subset__of.html", null ],
        [ "sum", "structutils_1_1meta_1_1sum.html", null ],
        [ "var", "classutils_1_1meta_1_1var.html", "classutils_1_1meta_1_1var" ]
      ] ],
      [ "shift_behavior", "namespaceutils_1_1shift__behavior.html", [
        [ "checked", "structutils_1_1shift__behavior_1_1checked.html", "structutils_1_1shift__behavior_1_1checked" ],
        [ "circular", "structutils_1_1shift__behavior_1_1circular.html", "structutils_1_1shift__behavior_1_1circular" ],
        [ "scalar", "structutils_1_1shift__behavior_1_1scalar.html", "structutils_1_1shift__behavior_1_1scalar" ],
        [ "standard", "structutils_1_1shift__behavior_1_1standard.html", "structutils_1_1shift__behavior_1_1standard" ]
      ] ],
      [ "always_false", "structutils_1_1always__false.html", null ],
      [ "always_true", "structutils_1_1always__true.html", null ],
      [ "apply_qualifiers", "structutils_1_1apply__qualifiers.html", "structutils_1_1apply__qualifiers" ],
      [ "arguments_of", "structutils_1_1arguments__of.html", null ],
      [ "arguments_of< R(Args...)>", "structutils_1_1arguments__of_3_01R_07Args_8_8_8_08_4.html", "structutils_1_1arguments__of_3_01R_07Args_8_8_8_08_4" ],
      [ "arity", "structutils_1_1arity.html", null ],
      [ "arity_of", "structutils_1_1arity__of.html", null ],
      [ "arity_of< R(Args...)>", "structutils_1_1arity__of_3_01R_07Args_8_8_8_08_4.html", null ],
      [ "as", "structutils_1_1as.html", "structutils_1_1as" ],
      [ "asg_wrap", "structutils_1_1asg__wrap.html", "structutils_1_1asg__wrap" ],
      [ "asg_wrap< Op, void >", "structutils_1_1asg__wrap_3_01Op_00_01void_01_4.html", "structutils_1_1asg__wrap_3_01Op_00_01void_01_4" ],
      [ "basic_obj_ptr", "classutils_1_1basic__obj__ptr.html", "classutils_1_1basic__obj__ptr" ],
      [ "basic_static_string", "structutils_1_1basic__static__string.html", "structutils_1_1basic__static__string" ],
      [ "bind", "structutils_1_1bind.html", "structutils_1_1bind" ],
      [ "default_array_deleter", "structutils_1_1default__array__deleter.html", "structutils_1_1default__array__deleter" ],
      [ "default_deleter", "structutils_1_1default__deleter.html", "structutils_1_1default__deleter" ],
      [ "deleter", "structutils_1_1deleter.html", "structutils_1_1deleter" ],
      [ "disabled_deleter", "structutils_1_1disabled__deleter.html", "structutils_1_1disabled__deleter" ],
      [ "dyn_method", "classutils_1_1dyn__method.html", null ],
      [ "dyn_method< R(Args...)>", "classutils_1_1dyn__method_3_01R_07Args_8_8_8_08_4.html", null ],
      [ "dyn_method< R(ObjPtr, Args...)>", "classutils_1_1dyn__method_3_01R_07ObjPtr_00_01Args_8_8_8_08_4.html", "classutils_1_1dyn__method_3_01R_07ObjPtr_00_01Args_8_8_8_08_4" ],
      [ "follow", "structutils_1_1follow.html", "structutils_1_1follow" ],
      [ "fptr", "classutils_1_1fptr.html", "classutils_1_1fptr" ],
      [ "function_decay", "structutils_1_1function__decay.html", null ],
      [ "function_decay< R(Args...) noexcept >", "structutils_1_1function__decay_3_01R_07Args_8_8_8_08_01noexcept_01_4.html", "structutils_1_1function__decay_3_01R_07Args_8_8_8_08_01noexcept_01_4" ],
      [ "function_decay< R(Args...)>", "structutils_1_1function__decay_3_01R_07Args_8_8_8_08_4.html", "structutils_1_1function__decay_3_01R_07Args_8_8_8_08_4" ],
      [ "function_decay< T >", "structutils_1_1function__decay_3_01T_01_4.html", null ],
      [ "has_implemented", "structutils_1_1has__implemented.html", null ],
      [ "integer", "structutils_1_1integer.html", "structutils_1_1integer" ],
      [ "is_equiv", "structutils_1_1is__equiv.html", null ],
      [ "is_lossless_convertible", "structutils_1_1is__lossless__convertible.html", null ],
      [ "is_same_width", "structutils_1_1is__same__width.html", null ],
      [ "is_tagged", "structutils_1_1is__tagged.html", null ],
      [ "is_template_instance", "structutils_1_1is__template__instance.html", null ],
      [ "is_template_instance< Tmpl, Tmpl< Ts... > >", "structutils_1_1is__template__instance_3_01Tmpl_00_01Tmpl_3_01Ts_8_8_8_01_4_01_4.html", null ],
      [ "ivtable", "structutils_1_1ivtable.html", "structutils_1_1ivtable" ],
      [ "key", "classutils_1_1key.html", null ],
      [ "lambda_decay", "structutils_1_1lambda__decay.html", null ],
      [ "lambda_decay< R(&)(Args...) noexcept >", "structutils_1_1lambda__decay_3_01R_07_6_08_07Args_8_8_8_08_01noexcept_01_4.html", "structutils_1_1lambda__decay_3_01R_07_6_08_07Args_8_8_8_08_01noexcept_01_4" ],
      [ "lambda_decay< R(&)(Args...)>", "structutils_1_1lambda__decay_3_01R_07_6_08_07Args_8_8_8_08_4.html", "structutils_1_1lambda__decay_3_01R_07_6_08_07Args_8_8_8_08_4" ],
      [ "lambda_decay< T >", "structutils_1_1lambda__decay_3_01T_01_4.html", null ],
      [ "make_fundamental", "structutils_1_1make__fundamental.html", null ],
      [ "make_fundamental< T >", "structutils_1_1make__fundamental_3_01T_01_4.html", "structutils_1_1make__fundamental_3_01T_01_4" ],
      [ "owning", "structutils_1_1owning.html", null ],
      [ "post_decrement", "structutils_1_1post__decrement.html", "structutils_1_1post__decrement" ],
      [ "post_decrement<>", "structutils_1_1post__decrement_3_4.html", "structutils_1_1post__decrement_3_4" ],
      [ "post_increment", "structutils_1_1post__increment.html", "structutils_1_1post__increment" ],
      [ "post_increment<>", "structutils_1_1post__increment_3_4.html", "structutils_1_1post__increment_3_4" ],
      [ "pre_decrement", "structutils_1_1pre__decrement.html", "structutils_1_1pre__decrement" ],
      [ "pre_decrement< void >", "structutils_1_1pre__decrement_3_01void_01_4.html", "structutils_1_1pre__decrement_3_01void_01_4" ],
      [ "pre_increment", "structutils_1_1pre__increment.html", "structutils_1_1pre__increment" ],
      [ "pre_increment< void >", "structutils_1_1pre__increment_3_01void_01_4.html", "structutils_1_1pre__increment_3_01void_01_4" ],
      [ "promote", "structutils_1_1promote.html", "structutils_1_1promote" ],
      [ "promote< void >", "structutils_1_1promote_3_01void_01_4.html", "structutils_1_1promote_3_01void_01_4" ],
      [ "qualifiers_of", "structutils_1_1qualifiers__of.html", "structutils_1_1qualifiers__of" ],
      [ "result_of", "structutils_1_1result__of.html", null ],
      [ "result_of< R(Args...)>", "structutils_1_1result__of_3_01R_07Args_8_8_8_08_4.html", "structutils_1_1result__of_3_01R_07Args_8_8_8_08_4" ],
      [ "sane_promotion", "structutils_1_1sane__promotion.html", "structutils_1_1sane__promotion" ],
      [ "shift_left", "structutils_1_1shift__left.html", "structutils_1_1shift__left" ],
      [ "shift_left< void >", "structutils_1_1shift__left_3_01void_01_4.html", "structutils_1_1shift__left_3_01void_01_4" ],
      [ "shift_left_asg", "structutils_1_1shift__left__asg.html", "structutils_1_1shift__left__asg" ],
      [ "shift_left_asg< void >", "structutils_1_1shift__left__asg_3_01void_01_4.html", "structutils_1_1shift__left__asg_3_01void_01_4" ],
      [ "shift_right", "structutils_1_1shift__right.html", "structutils_1_1shift__right" ],
      [ "shift_right< void >", "structutils_1_1shift__right_3_01void_01_4.html", "structutils_1_1shift__right_3_01void_01_4" ],
      [ "shift_right_asg", "structutils_1_1shift__right__asg.html", "structutils_1_1shift__right__asg" ],
      [ "shift_right_asg< void >", "structutils_1_1shift__right__asg_3_01void_01_4.html", "structutils_1_1shift__right__asg_3_01void_01_4" ],
      [ "stale_class", "structutils_1_1stale__class.html", "structutils_1_1stale__class" ],
      [ "trivial_semaphore", "structutils_1_1trivial__semaphore.html", "structutils_1_1trivial__semaphore" ],
      [ "unique_resource", "classutils_1_1unique__resource.html", "classutils_1_1unique__resource" ],
      [ "unique_resource_sync_t", "structutils_1_1unique__resource__sync__t.html", null ],
      [ "vtable", "structutils_1_1vtable.html", "structutils_1_1vtable" ],
      [ "with", "structutils_1_1with.html", "structutils_1_1with" ]
    ] ]
];