var modules =
[
    [ "utils::pmr::arena_allocator::arena_allocator", "group__utilspmrarena__allocatorconstructors.html", "group__utilspmrarena__allocatorconstructors" ],
    [ "utils::pmr::stack_allocator::stack_allocator", "group__utilspmrstack__allocatorconstructors.html", "group__utilspmrstack__allocatorconstructors" ],
    [ "utils::interval_endpoint::operator<=>, utils::interval_endpoint::compare", "group__utilsintervalendpointcomparison.html", "group__utilsintervalendpointcomparison" ],
    [ "utils::interval::operator<=>, utils::interval::compare", "group__utilsintervalcomparison.html", "group__utilsintervalcomparison" ],
    [ "utils::segment_tree::segment_tree", "group__segment__treeconstructors.html", "group__segment__treeconstructors" ],
    [ "utils::segment_tree::~segment_tree", "group__segment__treedestructors.html", "group__segment__treedestructors" ],
    [ "= utils::segment_tree::operator=", "group__segment__treeoperator.html", "group__segment__treeoperator" ],
    [ "utils::segment_tree::at", "group__segment__treeat.html", "group__segment__treeat" ],
    [ "utils::segment_tree::begin, utils::segment_tree::cbegin, utils::segment_tree::end, utils::segment_tree::cend, utils::segment_tree::rbegin, utils::segment_tree::crbegin, utils::segment_tree::rend, utils::segment_tree::crend", "group__segment__treeiterators.html", "group__segment__treeiterators" ],
    [ "utils::segment_tree::make_update", "group__segment__treemake__update.html", "group__segment__treemake__update" ],
    [ "utils::segment_tree::aggregate", "group__segment__treeaggregate.html", "group__segment__treeaggregate" ],
    [ "utils::segment_tree::total", "group__segment__treetotal.html", "group__segment__treetotal" ],
    [ "utils::is_integer_like", "group__is__integer__like.html", "group__is__integer__like" ],
    [ "utils::width_of", "group__width__of.html", "group__width__of" ],
    [ "utils::sane_common_type", "group__sane__common__type.html", "group__sane__common__type" ],
    [ "utils::is_same_sign", "group__is__same__sign.html", "group__is__same__sign" ],
    [ "utils::epsilon_of", "group__epsilon__of.html", "group__epsilon__of" ],
    [ "utils::is_lossless_convertible", "group__is__lossless__convertible.html", "group__is__lossless__convertible" ],
    [ "utils::integer::to_underlying", "group__integerto__underlying.html", "group__integerto__underlying" ],
    [ "utils::integer::integer", "group__integerinteger.html", "group__integerinteger" ],
    [ "utils::integer::operator==, utils::integer::operator<=>", "group__integeroperatorcomparison.html", "group__integeroperatorcomparison" ],
    [ "utils::integer::operator U&, utils::integer::operator const U&, utils::integer::operator U&&, utils::integer::operator const U&&", "group__integeroperatorconversion.html", "group__integeroperatorconversion" ],
    [ "utils::max_align", "group__utilsmax__align.html", "group__utilsmax__align" ],
    [ "utils::meta::is_tuple", "group__metais__tuple.html", "group__metais__tuple" ],
    [ "utils::meta::pack", "group__metapack.html", "group__metapack" ],
    [ "utils::meta::smart_pack", "group__metasmart__pack.html", "group__metasmart__pack" ],
    [ "utils::meta::make_tuple", "group__metamake__tuple.html", "group__metamake__tuple" ],
    [ "utils::meta::actual_index", "group__metaactual__index.html", "group__metaactual__index" ],
    [ "utils::meta::at", "group__metaat.html", "group__metaat" ],
    [ "utils::meta::search", "group__metasearch.html", "group__metasearch" ],
    [ "utils::meta::contained_in", "group__metacontained__in.html", "group__metacontained__in" ],
    [ "utils::meta::concat", "group__metaconcat.html", "group__metaconcat" ],
    [ "utils::meta::slice", "group__metaslice.html", "group__metaslice" ],
    [ "utils::meta::insert", "group__metainsert.html", "group__metainsert" ],
    [ "utils::meta::erase", "group__metaerase.html", "group__metaerase" ],
    [ "utils::meta::replace", "group__metareplace.html", "group__metareplace" ],
    [ "utils::meta::infer", "group__metainfer.html", "group__metainfer" ],
    [ "utils::meta::map", "group__metamap.html", "group__metamap" ],
    [ "utils::meta::reduce", "group__metareduce.html", "group__metareduce" ],
    [ "utils::meta::sum", "group__metasum.html", "group__metasum" ],
    [ "utils::meta::product", "group__metaproduct.html", "group__metaproduct" ],
    [ "utils::meta::extract", "group__metaextract.html", "group__metaextract" ],
    [ "utils::meta::rebind", "group__metarebind.html", "group__metarebind" ],
    [ "utils::meta::subset_of", "group__metasubset__of.html", "group__metasubset__of" ],
    [ "utils::meta::strict_subset_of", "group__metastrict__subset__of.html", "group__metastrict__subset__of" ],
    [ "utils::qualifiers_of", "group__utilsqualifiers__of.html", "group__utilsqualifiers__of" ],
    [ "utils::apply_qualifiers", "group__utilsapply__qualifiers.html", "group__utilsapply__qualifiers" ],
    [ "utils::follow", "group__utilsfollow.html", "group__utilsfollow" ],
    [ "utils::is_equiv", "group__utilsis__equiv.html", "group__utilsis__equiv" ],
    [ "utils::is_template_instance", "group__utilsis__template__instance.html", "group__utilsis__template__instance" ],
    [ "utils::explicitly_convertible_to", "group__utilsexplicitly__convertible__to.html", "group__utilsexplicitly__convertible__to" ],
    [ "utils::make_integer_range", "group__utilsmake__integer__range.html", "group__utilsmake__integer__range" ],
    [ "utils::is_tagged", "group__utilsis__tagged.html", "group__utilsis__tagged" ]
];