name: Release
on: [ release, workflow_dispatch ]
jobs:
  doxygenize:
    name: Generate Doxygen documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Clone theme
        run: 'git submodule add https://github.com/jothepro/doxygen-awesome-css.git'
      - name: Doxygenize
        uses: langroodi/doxygenize@v1.7.0
        with:
          htmloutput: './'